version: "3.8"
services:
  mongodb:
    image: "mongo"
  backend:
    build: .
    ports:
      - 8080:8080
  frontend:
    build: ./client
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
 